tasks:
  - init: yarn install
    command: couchdb -b && cp ./server/config-example.js ./server/config.js && sleep 5 && /bin/bash ./script/initcouch.sh && sleep 1 && yarn run start
image:
  file: .gitpod.Dockerfile
