image:
  file: .gitpod.Dockerfile

tasks:
  - init: yarn install && yarn run build && /usr/bin/couchdb -b
    command: yarn run start

# Ports to expose on workspace startup (optional)
ports:
  - port: 5400
    onOpen: open-preview
